/**
 * DataStack — RDS Postgres + ElastiCache Redis + S3 images bucket
 * + Secrets Manager entries.
 *
 * Design choices:
 *
 *   - RDS Postgres 16, t4g.micro for dev. `publiclyAccessible: true`
 *     is the brief's deliberate decision — the SG (from NetworkStack)
 *     locks inbound to App Runner + dev IPs only. Auto-generated
 *     password lives in Secrets Manager from creation, not exported
 *     anywhere else.
 *
 *   - ElastiCache Serverless Redis. Auto-scales, no instance sizing
 *     to worry about. Subnet IDs from NetworkStack's public subnets.
 *
 *   - S3 images bucket: `ai-content-images-${env}`. BLOCK_ALL public,
 *     S3-managed encryption. CloudFront OAC is wired up in EdgeStack;
 *     the bucket policy that allows CloudFront principal lands there.
 *
 *   - Secrets Manager: three entries.
 *       * `magnacms-${env}-jwt-secret` — auto-generated by CDK using
 *         generateSecretString (hex, 32 bytes). Avoids the manual
 *         post-deploy population the original plan required.
 *       * `magnacms-${env}-openai-api-key` — created empty. User
 *         populates manually via console.
 *       * RDS auto-creates its own password secret; we just reference
 *         the secret ARN downstream.
 *
 * Outputs expose ARNs and connection strings as `CfnOutput` so other
 * stacks can wire to them without circular dependencies. The bucket
 * is exported as a property (same-app cross-stack pattern) so
 * EdgeStack can attach the OAC policy.
 */

import {
  CfnOutput,
  Duration,
  RemovalPolicy,
  SecretValue,
  Stack,
  type StackProps,
} from "aws-cdk-lib";
import {
  InstanceClass,
  InstanceSize,
  InstanceType,
  type SecurityGroup,
  SubnetType,
  type Vpc,
} from "aws-cdk-lib/aws-ec2";
import {
  Credentials,
  DatabaseInstance,
  DatabaseInstanceEngine,
  ParameterGroup,
  PostgresEngineVersion,
} from "aws-cdk-lib/aws-rds";
import { BlockPublicAccess, Bucket, BucketEncryption } from "aws-cdk-lib/aws-s3";
import { Secret } from "aws-cdk-lib/aws-secretsmanager";
import type { Construct } from "constructs";

import type { EnvConfig } from "./config";

export interface DataStackProps extends StackProps {
  cfg: EnvConfig;
  vpc: Vpc;
  sgRds: SecurityGroup;
  // Note: sgRedis was previously consumed here to attach to the
  // ElastiCache cluster. The Redis cluster has been removed (see
  // commit-log) — the backend runs with USE_REDIS=false and pays
  // for nothing it doesn't use. `sgRedis` still exists in
  // NetworkStack so the VPC-connector + Redis revival path is
  // unchanged when Phase 11 lights it up.
}

export class DataStack extends Stack {
  public readonly rdsInstance: DatabaseInstance;
  public readonly imagesBucket: Bucket;
  public readonly jwtSecret: Secret;
  public readonly openaiApiKeySecret: Secret;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    const { cfg, vpc, sgRds } = props;

    // --- RDS Postgres ---
    // Parameter group forcing TLS on every connection. The RDS SG is
    // open to 0.0.0.0/0 (NetworkStack) because App Runner has no stable
    // egress prefix list to allowlist; `rds.force_ssl=1` is what makes
    // "auth + SSL is the gate" actually true server-side. The backend
    // also passes `?ssl=require` in the assembled DSN
    // (`app/core/aws_secrets.py`) — belt + suspenders.
    const pgEngine = DatabaseInstanceEngine.postgres({
      version: PostgresEngineVersion.VER_16_3,
    });
    const pgParams = new ParameterGroup(this, "PgParams", {
      engine: pgEngine,
      description: "Postgres parameter group - forces TLS on all connections",
      parameters: {
        "rds.force_ssl": "1",
      },
    });

    this.rdsInstance = new DatabaseInstance(this, "Postgres", {
      engine: pgEngine,
      parameterGroup: pgParams,
      instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: SubnetType.PUBLIC },
      securityGroups: [sgRds],
      publiclyAccessible: true,
      allocatedStorage: cfg.rdsAllocatedStorageGb,
      storageEncrypted: true,
      backupRetention: cfg.rdsBackupRetention,
      // Auto-generated by CDK; readable from Secrets Manager only.
      credentials: Credentials.fromGeneratedSecret("magnacms_app", {
        secretName: `magnacms-${cfg.envName}-rds-credentials`,
      }),
      databaseName: "magnacms",
      // Dev: easy teardown. Prod will override to RETAIN.
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
      deleteAutomatedBackups: cfg.envName === "dev",
      deletionProtection: cfg.envName !== "dev",
    });

    // --- ElastiCache Serverless Redis (removed) ---
    // Previously provisioned here, but the backend ships with
    // USE_REDIS=false and App Runner has no VPC connector — the
    // cluster was unreachable AND being billed (~$60/month).
    // When Phase 11 wires the VPC connector + refresh-token blocklist,
    // re-add the `CfnServerlessCache` + `CfnSubnetGroup` block (the
    // `sgRedis` in NetworkStack is still in place for that day).

    // --- S3 bucket for AI-generated images ---
    // S3 bucket names are globally unique. Append the account ID so
    // a generic prefix like "ai-content-images-dev" — which someone
    // else might already own worldwide — never collides on first
    // deploy. Multiple AWS accounts deploying this stack each get
    // their own distinct bucket name.
    this.imagesBucket = new Bucket(this, "ImagesBucket", {
      bucketName: `${cfg.imagesBucketBaseName}-${cfg.envName}-${this.account}`,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      // Block direct ACL writes — bucket policy + CloudFront OAC is
      // the only access path. The OAC policy is attached in EdgeStack.
      enforceSSL: true,
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
      autoDeleteObjects: cfg.envName === "dev",
      lifecycleRules: [
        // Move infrequently-accessed images to cheaper storage after 90d.
        // (No expiration — these are user-owned assets.)
        {
          id: "transition-to-ia",
          enabled: true,
          transitions: [
            {
              storageClass: { value: "STANDARD_IA" },
              transitionAfter: Duration.days(90),
            },
          ],
        },
      ],
    });

    // --- Secrets Manager entries ---
    this.jwtSecret = new Secret(this, "JwtSecret", {
      secretName: `magnacms-${cfg.envName}-jwt-secret`,
      description: "JWT signing secret. 32 random bytes, hex-encoded.",
      generateSecretString: {
        // 64 hex chars from `openssl rand -hex 32`. Excludes characters
        // that could trip JSON escaping when the value flows through
        // CloudFormation outputs.
        passwordLength: 64,
        excludePunctuation: true,
        excludeCharacters: '"@/\\\' ',
        // The backend's config validator (Shannon-entropy check at
        // bits/byte >= 4.5) will accept this. Hex output from
        // generateSecretString is high-entropy by construction.
      },
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
    });

    this.openaiApiKeySecret = new Secret(this, "OpenaiApiKeySecret", {
      secretName: `magnacms-${cfg.envName}-openai-api-key`,
      description:
        "OpenAI API key (sk-proj-...). Populated manually via console " +
        "after first deploy.",
      // Explicit placeholder value so the backend's
      // _reject_weak_secrets_outside_local validator fails fast at
      // App Runner boot time. Without this, CDK defaults to a random
      // 32-char password which passes the placeholder check and
      // silently runs with a fake key until the first OpenAI call.
      // SecretValue.unsafePlainText embeds the string in the CFN
      // template, which is fine for an explicit placeholder.
      secretStringValue: SecretValue.unsafePlainText(
        "sk-proj-REPLACE_ME-paste-the-real-key-via-console-before-first-deploy",
      ),
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
    });

    // --- Outputs for downstream stacks + the DEPLOY.md runbook ---
    new CfnOutput(this, "RdsEndpoint", {
      value: this.rdsInstance.dbInstanceEndpointAddress,
      exportName: `${id}-rds-endpoint`,
    });
    new CfnOutput(this, "RdsPort", {
      value: this.rdsInstance.dbInstanceEndpointPort,
      exportName: `${id}-rds-port`,
    });
    new CfnOutput(this, "RdsSecretArn", {
      value: this.rdsInstance.secret!.secretArn,
      exportName: `${id}-rds-secret-arn`,
    });
    new CfnOutput(this, "ImagesBucketName", {
      value: this.imagesBucket.bucketName,
      exportName: `${id}-images-bucket-name`,
    });
    new CfnOutput(this, "JwtSecretArn", {
      value: this.jwtSecret.secretArn,
      exportName: `${id}-jwt-secret-arn`,
    });
    new CfnOutput(this, "OpenaiApiKeySecretArn", {
      value: this.openaiApiKeySecret.secretArn,
      exportName: `${id}-openai-api-key-secret-arn`,
    });
  }
}
