/**
 * DataStack — RDS Postgres + ElastiCache Redis + S3 images bucket
 * + Secrets Manager entries.
 *
 * Design choices:
 *
 *   - RDS Postgres 16, t4g.micro for dev. `publiclyAccessible: true`
 *     is the brief's deliberate decision — the SG (from NetworkStack)
 *     locks inbound to App Runner + dev IPs only. Auto-generated
 *     password lives in Secrets Manager from creation, not exported
 *     anywhere else.
 *
 *   - ElastiCache Serverless Redis. Auto-scales, no instance sizing
 *     to worry about. Subnet IDs from NetworkStack's public subnets.
 *
 *   - S3 images bucket: `ai-content-images-${env}`. BLOCK_ALL public,
 *     S3-managed encryption. CloudFront OAC is wired up in EdgeStack;
 *     the bucket policy that allows CloudFront principal lands there.
 *
 *   - Secrets Manager: three entries.
 *       * `magnacms-${env}-jwt-secret` — auto-generated by CDK using
 *         generateSecretString (hex, 32 bytes). Avoids the manual
 *         post-deploy population the original plan required.
 *       * `magnacms-${env}-openai-api-key` — created empty. User
 *         populates manually via console.
 *       * RDS auto-creates its own password secret; we just reference
 *         the secret ARN downstream.
 *
 * Outputs expose ARNs and connection strings as `CfnOutput` so other
 * stacks can wire to them without circular dependencies. The bucket
 * is exported as a property (same-app cross-stack pattern) so
 * EdgeStack can attach the OAC policy.
 */

import { CfnOutput, Duration, RemovalPolicy, Stack, type StackProps } from "aws-cdk-lib";
import {
  InstanceClass,
  InstanceSize,
  InstanceType,
  type SecurityGroup,
  SubnetType,
  type Vpc,
} from "aws-cdk-lib/aws-ec2";
import { CfnServerlessCache, CfnSubnetGroup } from "aws-cdk-lib/aws-elasticache";
import {
  Credentials,
  DatabaseInstance,
  DatabaseInstanceEngine,
  PostgresEngineVersion,
} from "aws-cdk-lib/aws-rds";
import { BlockPublicAccess, Bucket, BucketEncryption } from "aws-cdk-lib/aws-s3";
import { Secret } from "aws-cdk-lib/aws-secretsmanager";
import type { Construct } from "constructs";

import type { EnvConfig } from "./config";

export interface DataStackProps extends StackProps {
  cfg: EnvConfig;
  vpc: Vpc;
  sgRds: SecurityGroup;
  sgRedis: SecurityGroup;
}

export class DataStack extends Stack {
  public readonly rdsInstance: DatabaseInstance;
  public readonly redisCluster: CfnServerlessCache;
  public readonly imagesBucket: Bucket;
  public readonly jwtSecret: Secret;
  public readonly openaiApiKeySecret: Secret;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    const { cfg, vpc, sgRds, sgRedis } = props;

    // --- RDS Postgres ---
    this.rdsInstance = new DatabaseInstance(this, "Postgres", {
      engine: DatabaseInstanceEngine.postgres({
        version: PostgresEngineVersion.VER_16_3,
      }),
      instanceType: InstanceType.of(InstanceClass.T4G, InstanceSize.MICRO),
      vpc,
      vpcSubnets: { subnetType: SubnetType.PUBLIC },
      securityGroups: [sgRds],
      publiclyAccessible: true,
      allocatedStorage: cfg.rdsAllocatedStorageGb,
      storageEncrypted: true,
      backupRetention: cfg.rdsBackupRetention,
      // Auto-generated by CDK; readable from Secrets Manager only.
      credentials: Credentials.fromGeneratedSecret("magnacms_app", {
        secretName: `magnacms-${cfg.envName}-rds-credentials`,
      }),
      databaseName: "magnacms",
      // Dev: easy teardown. Prod will override to RETAIN.
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
      deleteAutomatedBackups: cfg.envName === "dev",
      deletionProtection: cfg.envName !== "dev",
    });

    // --- ElastiCache Serverless Redis ---
    const redisSubnetGroup = new CfnSubnetGroup(this, "RedisSubnetGroup", {
      description: `Redis subnet group for ${cfg.envName}`,
      subnetIds: vpc.publicSubnets.map((s) => s.subnetId),
      cacheSubnetGroupName: `magnacms-${cfg.envName}-redis-subnets`,
    });
    this.redisCluster = new CfnServerlessCache(this, "Redis", {
      engine: "redis",
      serverlessCacheName: `magnacms-${cfg.envName}-redis`,
      subnetIds: vpc.publicSubnets.map((s) => s.subnetId),
      securityGroupIds: [sgRedis.securityGroupId],
      // ElastiCache Serverless scales storage + ECPU automatically;
      // we don't pin limits for dev. Prod can add usage caps via
      // CacheUsageLimits when it lands.
    });
    this.redisCluster.addDependency(redisSubnetGroup);

    // --- S3 bucket for AI-generated images ---
    // S3 bucket names are globally unique. Append the account ID so
    // a generic prefix like "ai-content-images-dev" — which someone
    // else might already own worldwide — never collides on first
    // deploy. Multiple AWS accounts deploying this stack each get
    // their own distinct bucket name.
    this.imagesBucket = new Bucket(this, "ImagesBucket", {
      bucketName: `${cfg.imagesBucketBaseName}-${cfg.envName}-${this.account}`,
      blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
      encryption: BucketEncryption.S3_MANAGED,
      // Block direct ACL writes — bucket policy + CloudFront OAC is
      // the only access path. The OAC policy is attached in EdgeStack.
      enforceSSL: true,
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
      autoDeleteObjects: cfg.envName === "dev",
      lifecycleRules: [
        // Move infrequently-accessed images to cheaper storage after 90d.
        // (No expiration — these are user-owned assets.)
        {
          id: "transition-to-ia",
          enabled: true,
          transitions: [
            {
              storageClass: { value: "STANDARD_IA" },
              transitionAfter: Duration.days(90),
            },
          ],
        },
      ],
    });

    // --- Secrets Manager entries ---
    this.jwtSecret = new Secret(this, "JwtSecret", {
      secretName: `magnacms-${cfg.envName}-jwt-secret`,
      description: "JWT signing secret. 32 random bytes, hex-encoded.",
      generateSecretString: {
        // 64 hex chars from `openssl rand -hex 32`. Excludes characters
        // that could trip JSON escaping when the value flows through
        // CloudFormation outputs.
        passwordLength: 64,
        excludePunctuation: true,
        excludeCharacters: '"@/\\\' ',
        // The backend's config validator (Shannon-entropy check at
        // bits/byte >= 4.5) will accept this. Hex output from
        // generateSecretString is high-entropy by construction.
      },
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
    });

    this.openaiApiKeySecret = new Secret(this, "OpenaiApiKeySecret", {
      secretName: `magnacms-${cfg.envName}-openai-api-key`,
      description:
        "OpenAI API key (sk-proj-...). Populated manually via console " +
        "after first deploy — DataStack creates the secret empty so " +
        "ComputeStack can reference its ARN.",
      // No generateSecretString → secret is created empty and stays
      // empty until the user pastes the real key.
      removalPolicy:
        cfg.envName === "dev" ? RemovalPolicy.DESTROY : RemovalPolicy.RETAIN,
    });

    // --- Outputs for downstream stacks + the DEPLOY.md runbook ---
    new CfnOutput(this, "RdsEndpoint", {
      value: this.rdsInstance.dbInstanceEndpointAddress,
      exportName: `${id}-rds-endpoint`,
    });
    new CfnOutput(this, "RdsPort", {
      value: this.rdsInstance.dbInstanceEndpointPort,
      exportName: `${id}-rds-port`,
    });
    new CfnOutput(this, "RdsSecretArn", {
      value: this.rdsInstance.secret!.secretArn,
      exportName: `${id}-rds-secret-arn`,
    });
    new CfnOutput(this, "RedisEndpoint", {
      value: this.redisCluster.attrEndpointAddress,
      exportName: `${id}-redis-endpoint`,
    });
    new CfnOutput(this, "ImagesBucketName", {
      value: this.imagesBucket.bucketName,
      exportName: `${id}-images-bucket-name`,
    });
    new CfnOutput(this, "JwtSecretArn", {
      value: this.jwtSecret.secretArn,
      exportName: `${id}-jwt-secret-arn`,
    });
    new CfnOutput(this, "OpenaiApiKeySecretArn", {
      value: this.openaiApiKeySecret.secretArn,
      exportName: `${id}-openai-api-key-secret-arn`,
    });
  }
}
