"""baseline schema

Revision ID: 68c9768f3798
Revises:
Create Date: 2026-05-14 17:55:23.786641

Adds the entire MVP schema in one shot — every table from §5 plus the two
things autogenerate cannot express:

  1. `CREATE EXTENSION IF NOT EXISTS citext` — must run before `users.email`
     (which is CITEXT) is created.
  2. A GIN full-text index on `content_pieces.rendered_text` using
     `to_tsvector('english', rendered_text)` — drives the dashboard's `?q=`
     full-text search.

All other indexes (including the two partial-WHERE ones) are autogenerated
straight from the model `__table_args__`.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68c9768f3798"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── Manual additions ─────────────────────────────────────────────────
    # citext is required by users.email. IF NOT EXISTS is idempotent so the
    # migration is safe to re-run after partial failures.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ── Autogenerated table DDL ──────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    op.create_table(
        "brand_voices",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tone_descriptors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "banned_words",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("sample_text", sa.Text(), nullable=True),
        sa.Column("target_audience", sa.String(length=500), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_brand_voices_user_id", "brand_voices", ["user_id"], unique=False)

    op.create_table(
        "improvements",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("improved_text", sa.Text(), nullable=False),
        sa.Column(
            "goal",
            sa.Enum(
                "shorter",
                "persuasive",
                "formal",
                "seo",
                "audience_rewrite",
                name="improvement_goal",
            ),
            nullable=False,
        ),
        sa.Column("new_audience", sa.String(length=500), nullable=True),
        sa.Column(
            "explanation",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "changes_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("original_word_count", sa.Integer(), nullable=True),
        sa.Column("improved_word_count", sa.Integer(), nullable=True),
        sa.Column("model_id", sa.String(length=120), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_improvements_user_id_created_at",
        "improvements",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )

    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)

    op.create_table(
        "usage_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "text_gen",
                "image_gen",
                "improve",
                "image_regen",
                "export",
                name="usage_event_type",
            ),
            nullable=False,
        ),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_usage_events_user_id_created_at",
        "usage_events",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )

    op.create_table(
        "content_pieces",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "content_type",
            sa.Enum(
                "blog_post",
                "linkedin_post",
                "ad_copy",
                "email",
                name="content_type",
            ),
            nullable=False,
        ),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("tone", sa.String(length=120), nullable=True),
        sa.Column("target_audience", sa.String(length=500), nullable=True),
        sa.Column("brand_voice_id", sa.UUID(), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("system_prompt_snapshot", sa.Text(), nullable=False),
        sa.Column("user_prompt_snapshot", sa.Text(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rendered_text", sa.Text(), nullable=False),
        sa.Column(
            "result_parse_status",
            sa.Enum("ok", "retried", "failed", name="result_parse_status"),
            nullable=False,
        ),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("model_id", sa.String(length=120), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["brand_voice_id"], ["brand_voices.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_content_pieces_user_id_active",
        "content_pieces",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_content_pieces_user_id_content_type",
        "content_pieces",
        ["user_id", "content_type"],
        unique=False,
    )
    op.create_index(
        "ix_content_pieces_user_id_created_at",
        "content_pieces",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )

    # GIN full-text expression index — drives the `?q=` dashboard search.
    # Declared on the model's __table_args__ so autogenerate sees parity
    # between the model and the live DB; emitted here via op.create_index
    # for parity with the autogenerated style.
    op.create_index(
        "ix_content_pieces_rendered_text_fts",
        "content_pieces",
        [sa.text("to_tsvector('english', rendered_text)")],
        unique=False,
        postgresql_using="gin",
    )

    op.create_table(
        "generated_images",
        sa.Column("content_piece_id", sa.UUID(), nullable=False),
        sa.Column("image_prompt", sa.Text(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("style", sa.String(length=64), nullable=True),
        sa.Column(
            "provider",
            sa.Enum("openai", "nova_canvas", name="image_provider"),
            nullable=False,
        ),
        sa.Column("model_id", sa.String(length=120), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("cdn_url", sa.String(length=1000), nullable=False),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["content_piece_id"], ["content_pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_generated_images_content_piece_id_created_at",
        "generated_images",
        ["content_piece_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_generated_images_current_per_piece",
        "generated_images",
        ["content_piece_id"],
        unique=True,
        postgresql_where=sa.text("is_current IS TRUE"),
    )


def downgrade() -> None:
    # Drop in reverse order so FKs unwind cleanly.
    op.drop_index(
        "ix_generated_images_current_per_piece",
        table_name="generated_images",
        postgresql_where=sa.text("is_current IS TRUE"),
    )
    op.drop_index("ix_generated_images_content_piece_id_created_at", table_name="generated_images")
    op.drop_table("generated_images")

    op.drop_index(
        "ix_content_pieces_rendered_text_fts",
        table_name="content_pieces",
        postgresql_using="gin",
    )
    op.drop_index("ix_content_pieces_user_id_created_at", table_name="content_pieces")
    op.drop_index("ix_content_pieces_user_id_content_type", table_name="content_pieces")
    op.drop_index(
        "ix_content_pieces_user_id_active",
        table_name="content_pieces",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("content_pieces")

    op.drop_index("ix_usage_events_user_id_created_at", table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_improvements_user_id_created_at", table_name="improvements")
    op.drop_table("improvements")
    op.drop_index("ix_brand_voices_user_id", table_name="brand_voices")
    op.drop_table("brand_voices")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    # ENUM types need explicit cleanup — they survive their owning tables.
    for enum_name in (
        "improvement_goal",
        "usage_event_type",
        "content_type",
        "result_parse_status",
        "image_provider",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # citext is left in place — it's harmless and may be used by other apps
    # sharing the database. If you truly want it gone:
    #   op.execute("DROP EXTENSION IF EXISTS citext")
